### ISSUE TITLE
resourcewarning: unclosed file

### ISSUE THREAD

**Issue by jugmac00** [greyli/bootstrap-flask#78]
reproduce
`tox -e py38`

```
test_local_resources (test_bootstrap_flask.BootstrapTestCase) ... /usr/lib/python3.8/unittest/case.py:633: ResourceWarning: unclosed file <_io.BufferedReader name='/home/jugmac00/Projects/bootstrap-flask/flask_bootstrap/static/css/bootstrap.min.css'>
  method()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3.8/unittest/case.py:633: ResourceWarning: unclosed file <_io.BufferedReader name='/home/jugmac00/Projects/bootstrap-flask/flask_bootstrap/static/js/bootstrap.min.js'>
  method()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3.8/unittest/case.py:633: ResourceWarning: unclosed file <_io.BufferedReader name='/home/jugmac00/Projects/bootstrap-flask/flask_bootstrap/static/jquery.min.js'>
  method()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
ok
```

**Update**
In order to use `tox`, pr #79 has to be merged, as `tox ` is currently broken.

**Comment by greyli** [comment]
Fixed in https://github.com/greyli/bootstrap-flask/pull/79.

**Comment by jugmac00** [comment]
Hi @greyli 

the `ResourceWarning` is still present. In #79 I only fixed the `tox` environments, so we are able to run the tests locally.

When running the tests, .e.g with `tox -e py38` the `ResourceWarning` still shows.

```
test_local_resources (test_bootstrap_flask.BootstrapTestCase) ... /usr/lib/python3.8/unittest/case.py:633: ResourceWarning: unclosed file <_io.BufferedReader name='/home/jugmac00/Projects/bootstrap-flask/flask_bootstrap/static/css/bootstrap.min.css'>
  method()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3.8/unittest/case.py:633: ResourceWarning: unclosed file <_io.BufferedReader name='/home/jugmac00/Projects/bootstrap-flask/flask_bootstrap/static/js/bootstrap.min.js'>
  method()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3.8/unittest/case.py:633: ResourceWarning: unclosed file <_io.BufferedReader name='/home/jugmac00/Projects/bootstrap-flask/flask_bootstrap/static/jquery.min.js'>
  method()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

I prepare a pull request.
